name: Deploy Backend to Railway

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**', 'Main.cpp', '*.h' ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to Railway
      uses: bervProject/railway-deploy@v1.0.3
      with:
        railway-token: ${{ secrets.RAILWAY_TOKEN }}
        service: backend
        working-directory: ./backend
